### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by agborkowski**
add li3 lib type

### CODE REVIEW

**Comment by scharrier** [comment]
As I stopped working on li3, I cannot test it. What does that change, from a composer and paths point view ? Can you just give me more details ?

(If you're interested in taking this repo over, I can give you the push rights ;))

**Comment by agborkowski** [comment]
composer just add support for li3 libs will works good :), for what framework u moved ?

**Comment by scharrier** [comment]
:+1:

(I moved to Ruby word 1 year ago ;))

**Comment by scharrier** [comment]
Thx for your contrib !

**Comment by agborkowski** [comment]
and how its going ? any impression compared to li3 ?

**Pull request merged**
